Append suffixes correctly for phpcpd
EdgedesignCZ/phpqa pull request #253
Opened 2023-01-17 11:39 UTC by mistermoper

Since phpcpd has released the 6.0 version the --names have been removed in favour of the new argument --suffix. This change has been adapted at PHPqa project but it needs a correction. 

CUrrently, the --suffix arguments is added by joining all the suffixes by commas. Example:

```bash
--suffix="*.php,*.theme,*.module"
```

But that syntax is not correct. This is the documentation of the suffix command from PHPcpd:

```bash
  --suffix <suffix> Include files with names ending in <suffix> in the analysis
                    (default: .php; can be given multiple times)
```

The suffix parameter only accepts one suffix, and if it is needed to add more suffixes, the --suffix parameter must be repeated. So, the example I shown below should be corrected to this:

```bash
--suffix="*.php,*.theme,*.module" --suffix="*.module" --suffix="*.theme"
```

This pull request fixes the usage of suffix to be added by repeating suffix arguments and not joining the suffixes by commas. Please review, thanks!

2023-01-18 18:08 UTC, zdenekdrahos requested changes

2023-01-18 18:08 UTC, zdenekdrahos commented on src/Tools/Analyzer/Phpcpd.php
> +                    $args[] = '--suffix "' . \Edge\QA\escapePath($name) . '"';
`escapePath` already adds quotes:

>  [Edge\QA\Task\ParallelExec] "/home/runner/work/phpqa/phpqa/vendor/bin/phpcpd"  --exclude=vendor --exclude=tests/.phpunit/fix-psalm-testcase.php "./" --min-lines 5 --min-tokens 70 --suffix "".php"" --log-pmd "build//phpcpd.xml"
> https://github.com/EdgedesignCZ/phpqa/actions/runs/3939897166/jobs/6740306675#step:7:27

Maybe using `sprintf` would make it more readable?

2023-02-02 09:55 UTC, mistermoper commented on src/Tools/Analyzer/Phpcpd.php
> +                    $args[] = '--suffix "' . \Edge\QA\escapePath($name) . '"';
Sounds better to me. I've just done the changes.

2023-02-02 10:00 UTC, mistermoper commented
I've done the requested changes. Please review, thanks!

2023-02-04 15:16 UTC, zdenekdrahos approved these changes

2023-02-04 15:18 UTC, merged